// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABY36mR4Oj9GDvLGmIWwaYm2ToRbsRHi0',
    appId: '1:581600224420:web:80657f09898846447f3231',
    messagingSenderId: '581600224420',
    projectId: 'baseball-fd12d',
    authDomain: 'baseball-fd12d.firebaseapp.com',
    storageBucket: 'baseball-fd12d.firebasestorage.app',
    measurementId: 'G-QT7FL1RDDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBayKXchzV5ADHeiBQ5txX7NI3CiRzyDng',
    appId: '1:581600224420:android:0eb9951e0c0fd8567f3231',
    messagingSenderId: '581600224420',
    projectId: 'baseball-fd12d',
    storageBucket: 'baseball-fd12d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkF92Sz3brQjXVEcdMTysF6EsTqYYAR8',
    appId: '1:581600224420:ios:9a1b69ce5dad52d97f3231',
    messagingSenderId: '581600224420',
    projectId: 'baseball-fd12d',
    storageBucket: 'baseball-fd12d.firebasestorage.app',
    androidClientId: '581600224420-92cc8tb49805p9hpo1fmqtrknntrf1r1.apps.googleusercontent.com',
    iosClientId: '581600224420-09ua8p6joptbvg67mrcvh428f77oh9v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flcProject',
  );
}
